### ISSUE TITLE
Not Responding to upsModel SNMP poll

### ISSUE THREAD

**Issue by Grimblee** [bytewriter/check-common-ups#1]
Hello,

I am trying to setup your script in my Icinga2 setup but I get the following error for all my APC PSUs:
> CRITICAL: 172.27.0.72  not responding to upsModel SNMP poll. snmpresult=

I've tried some SNMP walks and I have access to it: 
> snmpwalk -v 2c -c public 172.27.0.72 .1.3.6.1.2.1.1.2.0
> SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.318.1.3.4.6

But when I try the MIBmodel OID for APC:
> snmpwalk -v 2c -c public 172.27.0.72 .1.3.6.1.4.1.318.1.1.1.1.1.1.0
> SNMPv2-SMI::enterprises.318.1.1.1.1.1.1.0 = No Such Object available on this agent at this OID

Would it be possible to get some pointers on this ?

Thank you very much,

**Comment by bytewriter** [comment]
It sounds like the PSU does not have that OID. I do not have any PSU devices. I wrote this for the 150 or so UPSs I have. This info might help:
Get the make/model:
snmpget -v 2c -c public 172.27.0.72 .1.3.6.1.2.1.1.1.0
Check what OIDs are available in the APC range:
snmpwalk -v 2c -c public 172.27.0.72 .1.3.6.1.4.1.318

**Comment by Grimblee** [comment]
Hello,

So what I should do is find the correct OID for my model and adjust your script to match it ?

May it be possible it has something to do with those MIB files ?

Sry if this seems noobish, I'm quite new to SNMP ^^

Thank you,

**Comment by bytewriter** [comment]
Yes, you could modify the script to meet your needs. But it would probably be a lot more than just putting in the correct OID. Even if it works with that simple change, there are likely to be many differences between what you want icinga to display for a UPS vs a PSU. It might provide a rough guide if this is unfamiliar territory for you.
This does not look like a MIB file error to me. It looks like it came from the client. You could use -d to see the raw packets, but MIB file problems I see are usually complaints about MIB file structure, or the MIB specifies syntax <type>, but the host returned values not matching <type>.
Don't be discouraged. It won't take long for new to wear off.

**Comment by Grimblee** [comment]
Hooooo okey I understand now, this is a script for UPS and what I have is PDU xD

Seems logical my OIDs are different now, will see if I can find a PDU check and if not I'll delve into your script :p 

Thank you m8 !
